version: '3'
services:
  mongodb-api:
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - '.:/usr/src/app'
    ports:
      - '80:8080'
      - '5858:5858'
    depends_on:
      - mongodb


  mongodb:
    build:
      context: mongodb-docker/
    ports:
      - "27017:27017"